name: 'Build LaTex Document'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: wtfjoke/setup-tectonic@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic -X build
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: Thermodynamics.pdf
          path: build/Thermodynamics/
          if-no-files-found: error
  
